apiVersion: v1
kind: Secret
metadata:
  name: yellowpad-db
type: Opaque
stringData:
  POSTGRES_USER: yellowpad
  POSTGRES_PASSWORD: yellowpad
  DB_USER: yellowpad
  DB_PASSWORD: yellowpad
---
apiVersion: v1
kind: Secret
metadata:
  name: yellowpad-minio
type: Opaque
stringData:
  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: minioadmin
  MINIO_ACCESS_KEY: minioadmin
  MINIO_SECRET_KEY: minioadmin
